/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : C:\\Zlang\\src\\Zzparser\\Grammar\\yatgFW.g
 *     -                            On : 2010-03-04 16:18:39
 *     -           for the tree parser : yatgFWTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The tree parser yatgFW has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pyatgFW, which is returned from a call to yatgFWNew().
 *
 * The methods in pyatgFW are  as follows:
 *
 *  - void      pyatgFW->program(pyatgFW)
 *  - yatgFW_expr_return      pyatgFW->expr(pyatgFW)
 *  - void      pyatgFW->variable_decls(pyatgFW)
 *  - void      pyatgFW->type_decl(pyatgFW)
 *  - void      pyatgFW->decl(pyatgFW)
 *  - void      pyatgFW->if_expr(pyatgFW)
 *  - void      pyatgFW->while_loop(pyatgFW)
 *  - void      pyatgFW->do_loop(pyatgFW)
 *  - void      pyatgFW->for_loop(pyatgFW)
 *  - yatgFW_source_return      pyatgFW->source(pyatgFW)
 *  - void      pyatgFW->loop_exit(pyatgFW)
 *  - void      pyatgFW->loop_continue(pyatgFW)
 *  - void      pyatgFW->case_expr(pyatgFW)
 *  - void      pyatgFW->case_item(pyatgFW)
 *  - void      pyatgFW->struct_def(pyatgFW)
 *  - void      pyatgFW->member(pyatgFW)
 *  - void      pyatgFW->try_expr(pyatgFW)
 *  - void      pyatgFW->function_def(pyatgFW)
 *  - void      pyatgFW->fun(pyatgFW)
 *  - void      pyatgFW->function_return(pyatgFW)
 *  - void      pyatgFW->context_expr(pyatgFW)
 *  - void      pyatgFW->context(pyatgFW)
 *  - void      pyatgFW->set_context(pyatgFW)
 *  - void      pyatgFW->argT(pyatgFW)
 *  - void      pyatgFW->argument_expression_list(pyatgFW)
 *  - void      pyatgFW->unary_expression(pyatgFW)
 *  - void      pyatgFW->operand(pyatgFW)
 *  - void      pyatgFW->operand_op(pyatgFW)
 *  - void      pyatgFW->constant(pyatgFW)
 *  - void      pyatgFW->assignment_expression(pyatgFW)
 *  - yatgFW_cexprx_return      pyatgFW->cexprx(pyatgFW)
 *  - yatgFW_lvalue_return      pyatgFW->lvalue(pyatgFW)
 *  - yatgFW_assignment_operator_return      pyatgFW->assignment_operator(pyatgFW)
 *  - void      pyatgFW->expr_seq(pyatgFW)
 *  - yatgFW_expr_g_return      pyatgFW->expr_g(pyatgFW)
 *  - void      pyatgFW->box2(pyatgFW)
 *  - void      pyatgFW->point3(pyatgFW)
 *  - void      pyatgFW->point2(pyatgFW)
 *  - void      pyatgFW->array(pyatgFW)
 *  - void      pyatgFW->bitarray(pyatgFW)
 *  - void      pyatgFW->arrrange(pyatgFW)
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_yatgFW_H
#define _yatgFW_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

	#include "stdafx.h"

 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct yatgFW_Ctx_struct yatgFW, * pyatgFW;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */
typedef struct yatgFW_expr_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_expr_return;

typedef struct yatgFW_source_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_source_return;

typedef struct yatgFW_cexprx_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_cexprx_return;

typedef struct yatgFW_lvalue_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_lvalue_return;

typedef struct yatgFW_assignment_operator_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_assignment_operator_return;

typedef struct yatgFW_expr_g_return_struct
{
    pANTLR3_BASE_TREE       start;
    pANTLR3_BASE_TREE       stop;   
}
    yatgFW_expr_g_return;



/** Context tracking structure for yatgFW
 */
struct yatgFW_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_TREE_PARSER	    pTreeParser;


     void (*program)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_expr_return (*expr)	(struct yatgFW_Ctx_struct * ctx);
     void (*variable_decls)	(struct yatgFW_Ctx_struct * ctx);
     void (*type_decl)	(struct yatgFW_Ctx_struct * ctx);
     void (*decl)	(struct yatgFW_Ctx_struct * ctx);
     void (*if_expr)	(struct yatgFW_Ctx_struct * ctx);
     void (*while_loop)	(struct yatgFW_Ctx_struct * ctx);
     void (*do_loop)	(struct yatgFW_Ctx_struct * ctx);
     void (*for_loop)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_source_return (*source)	(struct yatgFW_Ctx_struct * ctx);
     void (*loop_exit)	(struct yatgFW_Ctx_struct * ctx);
     void (*loop_continue)	(struct yatgFW_Ctx_struct * ctx);
     void (*case_expr)	(struct yatgFW_Ctx_struct * ctx);
     void (*case_item)	(struct yatgFW_Ctx_struct * ctx);
     void (*struct_def)	(struct yatgFW_Ctx_struct * ctx);
     void (*member)	(struct yatgFW_Ctx_struct * ctx);
     void (*try_expr)	(struct yatgFW_Ctx_struct * ctx);
     void (*function_def)	(struct yatgFW_Ctx_struct * ctx);
     void (*fun)	(struct yatgFW_Ctx_struct * ctx);
     void (*function_return)	(struct yatgFW_Ctx_struct * ctx);
     void (*context_expr)	(struct yatgFW_Ctx_struct * ctx);
     void (*context)	(struct yatgFW_Ctx_struct * ctx);
     void (*set_context)	(struct yatgFW_Ctx_struct * ctx);
     void (*argT)	(struct yatgFW_Ctx_struct * ctx);
     void (*argument_expression_list)	(struct yatgFW_Ctx_struct * ctx);
     void (*unary_expression)	(struct yatgFW_Ctx_struct * ctx);
     void (*operand)	(struct yatgFW_Ctx_struct * ctx);
     void (*operand_op)	(struct yatgFW_Ctx_struct * ctx);
     void (*constant)	(struct yatgFW_Ctx_struct * ctx);
     void (*assignment_expression)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_cexprx_return (*cexprx)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_lvalue_return (*lvalue)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_assignment_operator_return (*assignment_operator)	(struct yatgFW_Ctx_struct * ctx);
     void (*expr_seq)	(struct yatgFW_Ctx_struct * ctx);
     yatgFW_expr_g_return (*expr_g)	(struct yatgFW_Ctx_struct * ctx);
     void (*box2)	(struct yatgFW_Ctx_struct * ctx);
     void (*point3)	(struct yatgFW_Ctx_struct * ctx);
     void (*point2)	(struct yatgFW_Ctx_struct * ctx);
     void (*array)	(struct yatgFW_Ctx_struct * ctx);
     void (*bitarray)	(struct yatgFW_Ctx_struct * ctx);
     void (*arrrange)	(struct yatgFW_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred2_yatgFW)	(struct yatgFW_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred43_yatgFW)	(struct yatgFW_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred88_yatgFW)	(struct yatgFW_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct yatgFW_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pyatgFW yatgFWNew         (pANTLR3_COMMON_TREE_NODE_STREAM instream);
ANTLR3_API pyatgFW yatgFWNewSSD      (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the tree parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define PIVOT      59
#define SS_PLUS_EQUAL      143
#define SS_CCBRACKET      154
#define SS_D_DOT      155
#define LETTER      159
#define EWHILE_EXP      15
#define SS_FSLASH      124
#define EIF_ELSE      11
#define CASE      39
#define KW_DEFAULT      101
#define ESEQ      7
#define P_P2      30
#define P_P3      31
#define UNDO      68
#define KW_WHERE      92
#define KW_FN      107
#define EOF      -1
#define STRING_LITERIAL      131
#define SS_PERCENT      125
#define KW_GLOBAL      79
#define EOL      162
#define EIF_COND      9
#define KW_UNDEFINED      138
#define EWHILE_CON      14
#define KW_LEVEL      111
#define KW_PARENT      115
#define LP_EXIT      36
#define RETURN      48
#define EDO      17
#define LP_EXIT_WITH      37
#define SS_D_BAR      145
#define KW_THEN      83
#define COORDSYS      57
#define SS_LT_EQUAL      151
#define BODY      51
#define KW_COORDSYS      113
#define SS_STAR      123
#define COMMENT      163
#define ARR_BIT      33
#define KW_EXIT      93
#define SS_GT      150
#define SS_COLON      100
#define ABOUT      60
#define KW_FUNCTION      106
#define ESRC_WHERE      28
#define EDO_CON      18
#define SS_COMMA      77
#define LINE_COMMENT      164
#define SS_DOT      126
#define ECATCH_EXP      47
#define KW_CATCH      104
#define P_BOX2      29
#define SS_D_EQUAL      147
#define LOCAL      61
#define KW_DO      84
#define SS_MINUS_EQUAL      144
#define SS_STAR_EQUAL      140
#define EWHILE      13
#define KW_ANIMATE      109
#define KW_ABOUT      116
#define EFOR      21
#define FUN_DEF      49
#define PRIM_EXP      76
#define SS_D_AMP      146
#define SS_CBRACKET      128
#define WS      161
#define SS_GT_EQUAL      152
#define SS_MINUS      122
#define LEVEL      64
#define SS_DQUOTE      157
#define EFOR_END      24
#define KW_TO      90
#define ETRY      45
#define KW_BY      91
#define ESRC_START      25
#define FUN      52
#define KW_LOCAL      78
#define EscapeSequence      156
#define SS_EQUAL      81
#define KW_ELSE      85
#define SS_EXC_EQUAL      148
#define MEMBER      44
#define MAPPED      53
#define ID_MORE      74
#define ARR_IND      35
#define SS_OPAREN      98
#define EDO_END      20
#define KW_UNSUPPLIED      139
#define KW_SELECTION      118
#define SS_CPAREN      99
#define KW_TRUE      133
#define HexDigit      160
#define KW_WITH      94
#define KW_PIVOT      117
#define CONTEXT      56
#define SELECTION      58
#define AT      70
#define VDECL      4
#define REF_OP      165
#define TIME      66
#define PARENT      63
#define VDEF      5
#define KW_MAPPED      105
#define SS_PLUS      121
#define KW_TIME      112
#define EFOR_SRC      22
#define KW_STRUCT      102
#define EWHILE_END      16
#define VVAL      6
#define KW_FOR      87
#define KW_WHILE      86
#define IDENTIFIER      80
#define OPERAND      71
#define LP_CONT      38
#define CASE_Exp      40
#define KW_RETURN      108
#define KW_SET      120
#define EFOR_EXP      23
#define KW_IN      88
#define HEX_LITERAL      130
#define ESRC_BY      27
#define ARR_A      32
#define KW_TRY      103
#define DIGIT      129
#define DOT      72
#define KW_IF      82
#define KW_UNDO      119
#define ARR_BIT_RANGE      34
#define WITH      67
#define ETRY_EXP      46
#define EIF_END      12
#define CASE_Item      41
#define WORLD      62
#define SS_OCBRACKET      153
#define KW_FALSE      134
#define KW_OFF      136
#define DEFAULT      42
#define FUN_NAME      50
#define KW_CONTINUE      95
#define SET      75
#define ARG_EXPR_L      73
#define STRUCT      43
#define SS_LT      149
#define EDO_EXP      19
#define KW_CASE      96
#define FUN_DEF_END      54
#define KW_COLLECT      89
#define EIN      69
#define SS_PERCENT_EQUAL      142
#define EIF      8
#define KW_WORLD      114
#define KW_ON      135
#define SS_HASH      132
#define ESQ_FSLASH_SQUOTE      158
#define KW_OK      137
#define EIF_THEN      10
#define KW_AT      110
#define KW_OF      97
#define SS_OBRACKET      127
#define ANIMATE      65
#define ESRC_TO      26
#define SS_FSLASH_EQUAL      141
#define STRING      55
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for yatgFW
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
